### ISSUE TITLE
Generate simulated samples from a genome abundance table 

### ISSUE THREAD

**Issue by fplaza** [CAMI-challenge/CAMISIM#126]
Hi,

I would like to create simulated samples by providing a genome abundance table to CAMISIM.
This implicates to start at phase 2 and skip the community design step.
These genomes are user-defined (not on the NCBI).

CAMISIM can take as input a taxonomic profile in BIOM format.
Yet, I am not sure the tool would accept a list of genomes and their expected abundance.

Is it something that can be considered? 

Thanks for your help,
Florian

**Comment by AlphaSquad** [comment]
Hi Florian,
this is something CAMISIM can do. You just need to provide the `distribution_file_paths` parameter with paths to tab-separated files (one for each sample you want to simulate) with genome name in the first column and the relative abundance on the second. The genome name here has to be the same genome ID you provide in the `genome_to_id` and `metadata` files. The `phase` parameter is not needed (and actually should remain `0`, since the `phase` functionality has been removed)

**Comment by fplaza** [comment]
Thanks for the prompt answer.

I have updated the configuration file accordingly
```
[Main]
seed=1
max_processors=54
dataset_id=test
output_directory=/output/
temp_directory=/tmp
gsa=True
pooled_gsa=True
anonymous=True
compress=1

[ReadSimulator]
readsim=tools/art_illumina-2.3.6/art_illumina
error_profiles=tools/art_illumina-2.3.6/profiles
samtools=tools/samtools-1.3/samtools
profile=mbarc
size=0.1
type=art
fragments_size_mean=270
fragment_size_standard_deviation=27

[CommunityDesign]
distribution_file_paths= /input/ERS4538508.sample_composition_wide.tsv

[community0]
metadata=/input/metadata.tsv
id_to_genome_file=/input/genome_to_id.tsv
```

Yet, CAMISIM crashes by trying to open a BIOM file that obviously does not exist.

```
$metagenome_from_profile.py -o output/ -c config.ini
Traceback (most recent call last):
  File "/usr/local/bin/metagenome_from_profile.py", line 95, in <module>
    config = GG.generate_input(args) # total number of genomes and path to updated config
  File "/usr/local/bin/scripts/get_genomes.py", line 385, in generate_input
    tax_profile = read_taxonomic_profile(args.profile, config, args.samples)
  File "/usr/local/bin/scripts/get_genomes.py", line 57, in read_taxonomic_profile
    table = biom.load_table(biom_profile)
  File "/usr/local/lib/python3.8/dist-packages/biom/parse.py", line 670, in load_table
    with biom_open(f) as fp:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/biom/util.py", line 439, in biom_open
    if os.path.getsize(fp) == 0:
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Am I missing something?

**Comment by AlphaSquad** [comment]
Oh, yeah sorry, you have to use the other `.py` file, i.e. `metagenomesimulation.py config.ini`. Also I am not 100% sure whether the whitespace in front of the paths could cause trouble. Also, if you provide only one distribution file, make sure that the number of samples is set to `1`, too.

**Comment by fplaza** [comment]
Thanks for the clarification.
Now CAMSIM crashes with another error message:
```
metagenomesimulation.py config.ini
ERROR: 'MetagenomeSimulation' object has no attribute '_number_of_communities'
```

Adding the parameter _number_of_communities=1_ to the  _[CommunityDesign]_ section does not fix it.

**Comment by AlphaSquad** [comment]
Hm, could you try filling out all the parameters that are in the `CommunityDesign` section in the `mini_config.ini` (i.e. `distribution_file_paths`, `ncbi_taxdump`, `strain_simulation_template` and `number_of_samples`), taking the values from this config file for `ncbi_taxdump` and `strain_simulation_template`?

**Comment by fplaza** [comment]
Indeed, some parameters are mandatory even if unused.
Now, CAMISIM crashes with another error message.
```
2022-01-04 19:48:16 ERROR: [MetagenomeSimulationPipeline] [Errno 2] No such file or directory: "/usr/local/bin/'/input/sample_composition.tsv'" in line 79
2022-01-04 19:48:16 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```

CAMI does not accept absolute paths. Seems like a bug to me. 
Could you fix this?

**Comment by AlphaSquad** [comment]
Hm yeah, absolute paths should work and they do for me. In your config file, does the path have the `'`? 
Unfortunately, this part of the config file is wrong, you need to remove these (like you did in the config file you posted). I updated the `mini_config` accordingly (No `'` and whitespace).

**Comment by fplaza** [comment]
There were obviously extra quotes.

There were obviously extra quotes.
Sorry about that.

I have a new error message:
```
root@6f671e7c4ff6:/usr/local/bin# metagenomesimulation.py /input/mini_config.ini
2022-01-05 15:26:50 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2022-01-05 15:26:50 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2022-01-05 15:26:50 INFO: [MetadataReader] Reading file: '/input/genome_to_id.tsv'
2022-01-05 19:55:37 INFO: [MetadataReader 61355713354] Reading file: '/input/metadata.tsv'
2022-01-05 19:55:37 INFO: [MetadataReader 31395689975] Reading file: '/output/internal/genome_locations.tsv'
2022-01-05 19:55:37 ERROR: [MetadataReader 31395689975] Key column is not unique! Key: 'GUT_GENOME000004'
2022-01-05 19:55:37 ERROR: [MetagenomeSimulationPipeline] "Key column is not unique! Key: 'GUT_GENOME000004'" in line 74
2022-01-05 19:55:37 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```

Yet, GUT_GENOME000004 is not a duplicated entry in the genome_to_id file:
```
root@6f671e7c4ff6:/usr/local/bin# grep GUT_GENOME000004 /input/genome_to_id.tsv
GUT_GENOME000004        /input/mgnify_genomes/MGYG-HGUT-00002/GUT_GENOME000004.fna
```

but it is in genome_locations.tsv:
```
root@6f671e7c4ff6:/usr/local/bin# grep GUT_GENOME000004 /output/internal/genome_locations.tsv
GUT_GENOME000004        /input/mgnify_genomes/MGYG-HGUT-00002/GUT_GENOME000004.fna
GUT_GENOME000004        /input/mgnify_genomes/MGYG-HGUT-00002/GUT_GENOME000004.fna
```

I guess it is because I did not clean up the output directory between runs?

**Comment by AlphaSquad** [comment]
Oh, yes unfortunately you will need to delete unfinished/crashed runs.

**Comment by fplaza** [comment]
Ok. Adding in the next release a warning message if the output directory is not empty would be helpful.

**Comment by AlphaSquad** [comment]
True. The next big release (something of a 2.0 version) will be a nextflow implementation which hopefully eliminates this problem. If it does not, having such a warning message is definitely useful, I agree.

**Comment by fplaza** [comment]
I finally managed to generate my first simulated sample!  
Thanks again for your help and your time!

**Comment by YiJessePi** [comment]
Hey Florian @fplaza,
I'm have a similar aim as yours (simulate reads from UHGG based on genome abundance table).
If you don't mind to share your final config file (I'm not how it should be look like for such a task with metagenomesimulation.py and an example of  a metadata file row when having no NCBI taxonomy it would be very very helpful!
Thanks!

**Comment by AlphaSquad** [comment]
If you are not using the taxonomy (i.e. you don't need "gold standards" for profiling), you can just use a random valid taxonomy ID for that column (e.g. 2). 
You will need to set the "max_strains_per_otu" option to the number of genomes you want to simulate then. 
Apart from that you can have a look at the `mini_config.ini` in the `defaults` folder, this config file should work out of the box using the `metagenomesimulation.py` script (`metagenomesimulation.py defaults/mini_config.ini`). It uses the `metadata.tsv` and `genome_to_id.tsv` files which you can also find in the `defaults/` folder (and which you can adapt for your needs then). You would need to remove the `#` on line 24 and provide your abundance files there.

Let me know if this helps!

**Comment by fplaza** [comment]
Hi @YiJessePi !

Below are the files.

**config.ini**
```
[Main]
seed=1
max_processors=54
dataset_id=test
output_directory=/output/
temp_directory=/tmp
gsa=True
pooled_gsa=True
anonymous=True
compress=1

[ReadSimulator]
readsim=tools/art_illumina-2.3.6/art_illumina
error_profiles=tools/art_illumina-2.3.6/profiles
samtools=tools/samtools-1.3/samtools
profile=mbarc
size=0.1
type=art
fragments_size_mean=270
fragment_size_standard_deviation=27

[CommunityDesign]
ncbi_taxdump=tools/ncbi-taxonomy_20170222.tar.gz
strain_simulation_template=scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
distribution_file_paths=/input/ERS4538508.sample_composition_wide.tsv
number_of_samples=1

[community0]
metadata=/input/metadata.tsv
id_to_genome_file=/input/genome_to_id.tsv
id_to_gff_file=
genomes_total=18220
genomes_real=18220
max_strains_per_otu=1
ratio=1
mode=differential
log_mu=1
log_sigma=2
gauss_mu=1
gauss_sigma=1
view=False
```

First lines of **metadata.tsv**
```
genome_ID       OTU     NCBI_ID novelty_category
GUT_GENOME000701        OTU_1   22      known strain
GUT_GENOME000485        OTU_1   22      known strain
GUT_GENOME085166        OTU_2   22      known strain
GUT_GENOME000008        OTU_2   22      known strain
GUT_GENOME000010        OTU_3   22      known strain
GUT_GENOME095976        OTU_3   22      known strain
GUT_GENOME150173        OTU_4   22      known strain
GUT_GENOME229700        OTU_4   22      known strain
```

First lines of **genome_to_id.tsv**
```
GUT_GENOME000485        /input/mgnify_genomes/MGYG-HGUT-00002/GUT_GENOME000485.fna
GUT_GENOME000701        /input/mgnify_genomes/MGYG-HGUT-00002/GUT_GENOME000701.fna
GUT_GENOME000008        /input/mgnify_genomes/MGYG-HGUT-00003/GUT_GENOME000008.fna
GUT_GENOME085166        /input/mgnify_genomes/MGYG-HGUT-00003/GUT_GENOME085166.fna
GUT_GENOME000010        /input/mgnify_genomes/MGYG-HGUT-00004/GUT_GENOME000010.fna
GUT_GENOME095976        /input/mgnify_genomes/MGYG-HGUT-00004/GUT_GENOME095976.fna
GUT_GENOME150173        /input/mgnify_genomes/MGYG-HGUT-00008/GUT_GENOME150173.fna
GUT_GENOME229700        /input/mgnify_genomes/MGYG-HGUT-00008/GUT_GENOME229700.fna
```

Command to generate data
`python3 metagenome_from_profile.py -c /input/config.ini -o /output`

**Comment by YiJessePi** [comment]
Thank you so much @fplaza and @AlphaSquad!
Adrian,
1. What do you mean by gold standard? assembly. If so, no I do not need (interested in simulating reads representing known community).
2. As for NCBI taxa and OTU- since I'm using genome from UHGG, I think I can assign NCBI taxa and species level OTU to most of the genomes, but just wondering how if ever it will affect the simulation from custom genomes?
3. I've executed the pipeline as suggested and it seems to work great. One technical question- is there a way to get pairs of fastq per sample? I'm getting fastq per genome if skipping anonymization OR interleaved fastq if doing anonymization. I can of course either concatenate the first OR split the second, but asking just in case...

Florian,
Why did you chose to execute metagenome_from_profile and not metagenomesimulation?

**Comment by AlphaSquad** [comment]
Sorry for not coming back to these questions earlier it seems like they evaded my inbox @YiJessePi 

1. The gold standard I was refering to was a profiling gold standard, i.e. the taxonomic composition of your sample. Since you start from a known composition, this is probably not of interest to you. Assembly gold standards are always produced, but you can just ignore them if they are of no interest to you.  

2. I am not entirely sure what you mean with "custom genomes". If you use pre-defined abundance tables then CAMISIM will simulate your genomes exactly with the given abundances and their taxonomy is not considered. If you use a 16S profile as input and do not manually provide reference genomes then CAMISIM will try to match the genomes from the profile with genomes from the RefSeq (up to family level) and will generate a warning if no reference genomes are found. You can provide custom databases (e.g. UHGG) for CAMISIM to also select genomes from. They need NCBI taxonomy IDs though.

3. That is an interesting point. Currently there is no way to generate two fastq files and to be honest providing this is not high on my priority list since it should be quite easy to split the interleaved files as you suggested.

Finally, I think Florians command is a typo since CAMISIM would need a profile as input for the `from_profile` mode and I assume he also ran `metagenomesimulation.py` since the original error in this Issue is directly linked to using the other `.py` file which will not work

**Comment by fplaza** [comment]
Indeed, the command line is wrong (bad copy/paste).
Sorry about that.
