### ISSUE TITLE
Database errors  running the default commands using docker on latest version of CAMISIM as of May 2022

### ISSUE THREAD

**Issue by elximo** [CAMI-challenge/CAMISIM#133]
All,

I have been trying to install CAMISIM on MacOS (M1 chip, arm64 arch). After several attempts of porting, I opted to use docker (latest version of cami/camisem). However, I still get a database error with the basic test command as follows:

```
docker run -it -v "/Users/myusername/software/CAMISIM/defaults:/input:rw" -v "/Users/myusername/software/CAMISIM/out/2002/:/output:rw"  cami/camisim:latest  metagenome_from_profile.py -p /input/mini.biom -o /output`
```

After the following part:

```Tree is loaded.
Updating database: /root/.etetoolkit/taxa.sqlite ...
2420000 generating entries... 
Uploading to /root/.etetoolkit/taxa.sqlite
```

I get this error:

```
Inserting synonyms:      90000Traceback (most recent call last):
  File "metagenome_from_profile.py", line 11, in <module>
    import scripts.get_genomes as GG
  File "/usr/local/bin/scripts/get_genomes.py", line 15, in <module>
    ncbi = NCBITaxa()
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 74, in __init__
    self.update_taxonomy_database()
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 101, in update_taxonomy_database
    update_db(self.dbfile)
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 659, in update_db
    upload_data(dbfile)
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 698, in upload_data
    db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spname))
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid
```

Kindly let me know if you need any more details. Could you please guide me to a fix?

On a kinda (un)related note, (I can open another ticket for this), I ported CAMISIM to my environment macOS Monterey 12.3.1 (M1 chip, arm64 arch using conda, and python 3.6). I changed few lines in the pythons scripts and recompiled Illumina art binary.

After running the following default test command, natively without docker:

```
python metagenome_from_profile.py -p defaults/mini.biom
```

While I get few warnings of these

```
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/Users/myusername/mambaforge/envs/camisimPy36/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1804984 was translated into 1417228
```
I get the following error, which I think is either related to the above docker database  error or may be related to the different version of Illumina_art I have compiled.

```
2022-05-12 12:16:50 WARNING: [root] Some OTUs could not be mapped
2022-05-12 12:16:51 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2022-05-12 12:16:51 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2022-05-12 12:16:51 INFO: [MetadataReader] Reading file: '/Users/myusername/software/CAMISIM/out/genome_to_id.tsv'
2022-05-12 12:16:59 INFO: [MetadataReader 62964723710] Reading file: '/Users/myusername/software/CAMISIM/out/metadata.tsv'
2022-05-12 12:16:59 INFO: [MetadataReader 85176660939] Reading file: '/Users/myusername/software/CAMISIM/out/internal/genome_locations.tsv'
2022-05-12 12:16:59 ERROR: [MetadataReader 85176660939] Key column is not unique! Key: 'Genome1.0'
2022-05-12 12:16:59 ERROR: [MetagenomeSimulationPipeline] "Key column is not unique! Key: 'Genome1.0'" in line 74
2022-05-12 12:16:59 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```
What is the version of Illumina art simulator binary used in CAMISIM? I compiled the most recent, _MountRainier_, source.

Your help is greatly appreciated.
Hazem Sharaf

**Comment by elximo** [comment]
No worries, I solved both issues.
The solution from issue #120 is no longer working as the branch has been merged and not available for retrieving. However, it is not been reflected yet in the latest docker image that I pulled using docker desktop client.
I still had to use the solution in ([Prunoideae/MitoFlex#2](https://github.com/Prunoideae/MitoFlex/issues/2)) just like OP in #120 .

As for the second issue, I deleted the output folder as  reported in issue . I have also recompiled Samtools 1.3, installed shuf from coreutils.
I also reviewed my commands history and I did not edit any files. I ended up using python 3.6 instead of 3.10. I have also installed most dependencies including the perl ones using conda.

You can delete this post.
