### ISSUE TITLE
Error on nanosim_profile while running with NanoSim

### ISSUE THREAD

**Issue by eparisis** [CAMI-challenge/CAMISIM#148]
Hi there, I've been trying to run Camisim with NanoSim to simulate ONT reads. I've tested the program with the art simulator and works but I can't figure out how to run it with NanoSim. The error I'm getting now seems to be related to the simulation profiles and nanosim cant locate them although the path is described in the config file. I'm using the suggested forked version of NanoSim as described in the Manual.

I run `metagenomesimulation.py config.ini` in the directory with the files I want to simulate and get this error:
```bash
2022-12-08 08:21:02 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2022-12-08 08:21:02 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2022-12-08 08:21:02 INFO: [MetadataReader] Reading file: '/home/DNAUserseq/datadrive/CAMISIM/test/genome_to_id.tsv'
2022-12-08 08:21:03 INFO: [MetagenomeSimulationPipeline] Design Communities
2022-12-08 08:21:03 INFO: [CommunityDesign] Drawing strains.
2022-12-08 08:21:03 INFO: [MetadataReader 48366305545] Reading file: '/home/DNAUserseq/datadrive/CAMISIM/test/meta_data.tsv'
2022-12-08 08:21:03 INFO: [MetadataReader 23794736001] Reading file: '/home/DNAUserseq/datadrive/CAMISIM/test/genome_to_id.tsv'
2022-12-08 08:21:03 INFO: [CommunityDesign] Validating raw sequence files!
2022-12-08 08:21:05 INFO: [NcbiTaxonomy] Building taxonomy tree...
2022-12-08 08:21:05 INFO: [NcbiTaxonomy] Reading 'nodes' file:  '/tmp/tmp85a5imj6/NCBI/nodes.dmp'
2022-12-08 08:21:12 INFO: [NcbiTaxonomy] Reading 'names' file:  '/tmp/tmp85a5imj6/NCBI/names.dmp'
2022-12-08 08:21:13 INFO: [NcbiTaxonomy] Reading 'merged' file: '/tmp/tmp85a5imj6/NCBI/merged.dmp'
2022-12-08 08:21:13 INFO: [NcbiTaxonomy] Done (9s)
2022-12-08 08:21:13 INFO: [MetagenomeSimulationPipeline] Move Genomes
2022-12-08 08:21:13 WARNING: [GenomePreparation 55852882930] File /home/DNAUserseq/datadrive/CAMISIM/test/out/source_genomes/GCF_000154385.1.fa existing, skipping
2022-12-08 08:21:13 WARNING: [GenomePreparation 55852882930] File /home/DNAUserseq/datadrive/CAMISIM/test/out/source_genomes/GCF_000146045.2.fa existing, skipping
2022-12-08 08:21:13 WARNING: [GenomePreparation 55852882930] File /home/DNAUserseq/datadrive/CAMISIM/test/out/source_genomes/GCF_000091045.1.fa existing, skipping
2022-12-08 08:21:13 INFO: [MetagenomeSimulationPipeline] Read simulation
2022-12-08 08:21:13 INFO: [GenomePreparation 59470663380] Reading distribution file
2022-12-08 08:21:13 INFO: [GenomePreparation 59470663380] Reading genome location file
2022-12-08 08:21:13 INFO: [GenomePreparation 59470663380] Simulating reads using ReadSimulationNanosim readsimulator...
2022-12-08 08:21:13 INFO: [GenomePreparation 59470663380] Simulating reads from GCF_000154385.1: '/home/DNAUserseq/datadrive/CAMISIM/test/out/source_genomes/GCF_000154385.1.fa'
2022-12-08 08:21:13 INFO: [GenomePreparation 59470663380] Simulating reads from GCF_000146045.2: '/home/DNAUserseq/datadrive/CAMISIM/test/out/source_genomes/GCF_000146045.2.fa'
2022-12-08 08:21:13 INFO: [GenomePreparation 59470663380] Simulating reads from GCF_000091045.1: '/home/DNAUserseq/datadrive/CAMISIM/test/out/source_genomes/GCF_000091045.1.fa'
Traceback (most recent call last):
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 716, in <module>
    main()
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 708, in main
    read_profile(number, model_prefix, perfect, max_readlength, min_readlength)
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 125, in read_profile
    with open(model_profile, 'r') as mod_profile:
FileNotFoundError: [Errno 2] No such file or directory: 'tools/nanosim_profile/ecoli_model_profile'
Traceback (most recent call last):
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 716, in <module>
    main()
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 708, in main
    read_profile(number, model_prefix, perfect, max_readlength, min_readlength)
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 125, in read_profile
    with open(model_profile, 'r') as mod_profile:
FileNotFoundError: [Errno 2] No such file or directory: 'tools/nanosim_profile/ecoli_model_profile'
Traceback (most recent call last):
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 716, in <module>
    main()
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 708, in main
    read_profile(number, model_prefix, perfect, max_readlength, min_readlength)
  File "/home/DNAUserseq/software/NanoSimCami/src/simulator.py", line 125, in read_profile
    with open(model_profile, 'r') as mod_profile:
FileNotFoundError: [Errno 2] No such file or directory: 'tools/nanosim_profile/ecoli_model_profile'
2022-12-08 08:21:14 INFO: [GenomePreparation 59470663380] Simulating reads finished
2022-12-08 08:21:14 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2022-12-08 08:21:14 INFO: [MetadataReader 28817666041] Reading file: '/home/DNAUserseq/datadrive/CAMISIM/test/out/internal/genome_locations.tsv'
2022-12-08 08:21:14 ERROR: [MetagenomeSimulationPipeline] Empty bam file list in line 106
2022-12-08 08:21:14 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```

This is my config file 
```bash
[Main]
# phase 0: community design + read simulator, 1: read simulator only
phase=0 
max_processors=8
output_directory=/home/DNAUserseq/datadrive/CAMISIM/test/out 
temp_directory=/home/DNAUserseq/datadrive/CAMISIM/test/tmp
# Gold standard assembly
gsa=True    
# Gold standard for all samples combined
pooled_gsa=True 
# Anonymize seqs
anonymous=False
# Compress levels
compress=1 
# id of dataset, used in foldernames and is prefix in anonymous sequences
dataset_id=RL

[ReadSimulator]
readsim=/home/DNAUserseq/software/NanoSimCami/src/simulator.py
error_profiles=/home/DNAUserseq/software/CAMISIM/tools/nanosim_profile
samtools=/usr/bin/samtools

#error profiles:
#for ART:
#HiSeq 150bp: hi150
#MBARC-26 150bp: mbarc
#custom profile (see below): own
#for wgsim:
#error rate as <float> (e.g. 0.05 for 5 0.000000e+00rror rate)
#blank for nanosim and wgsim
profile=
# Specify the samples size in Giga base pairs
size=0.2
# ReadSimulator choose: 'art', 'wgsim', 'nanosim', 'pbsim'
type=nanosim
# Paired end read, insert size (not applicable for nanosim)
fragments_size_mean=
fragment_size_standard_deviation=

[CommunityDesign]
distribution_file_paths=
ncbi_taxdump=/home/DNAUserseq/software/CAMISIM/tools/ncbi-taxonomy_20170222.tar.gz
strain_simulation_template=/home/DNAUserseq/software/CAMISIM/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
number_of_samples=1

[community0]
metadata=/home/DNAUserseq/datadrive/CAMISIM/test/meta_data.tsv
id_to_genome_file=/home/DNAUserseq/datadrive/CAMISIM/test/genome_to_id.tsv
id_to_gff_file=
genomes_total=3
genomes_real=3
max_strains_per_otu=1
# how many genomes per species taxon
ratio=1 
# replicates / timeseries_lognormal / timeseries_normal / differential
mode=differential 
log_mu=1 
log_sigma=2
gauss_mu=1
gauss_sigma=1
view=False

# If you want to create a second community with other stats jus add the
# above sequence and repeat
# [community1]
# ...
```

Any help on this one? 

Also is there a way to run CAMISIM with Docker and NanoSim since it isn't included in the image? How would the command look like?

**Comment by AlphaSquad** [comment]
Hi,
unfortunately our manual is not 100% up to date. NanoSim has received some significant updates which broke our code, we now recommend using NanoSim >=3.0 (https://github.com/bcgsc/NanoSim/releases/tag/v3.0.0).
For this to work, you will need to link to the `simulator.py` from that version and change the `type` to `nanosim3` in your config file. There is a pre-trained model for Nanosim3 in `tools/nanosim_profile/` called `training` which you can use. A excerpt from a working config file would look like this:
```
...
[ReadSimulator]
readsim=/path/to/your/simulator.py
error_profiles=tools/nanosim_profile/
profile=training
type=nanosim3
...
```
Regarding docker: This is a very good point which I had not considered so far. Currently there is not really a way to use the CAMISIM container with Nanosim. We are currently working on a major update to CAMISIM which will automatically install the correct Nanosim version(s) and should have a working Docker container; unfortunately we do not have a fixed date for a release, but we hope for early next year. The user manual will then be updated reflecting all the latest changes, too. I am sorry for the inconvenience.

**Comment by eparisis** [comment]
Thank you very much for your quick reply. Following your instructions, it seems to work now on my test dataset. Thanks a lot!

Just a quick note for anyone with similar problems, NanoSim seems to have some bugs with this training profile. I got the error code  `ModuleNotFoundError: No module named 'sklearn.neighbors.kde'` and fixed it by installing the older version of `scikit-learn` as described [here](https://github.com/bcgsc/NanoSim/issues/131#issuecomment-1093527283).

I do have another bit unrelated question to this specific topic about Camisim. In order to compare results from taxonomic profilers I'm going to need to convert their results into the Cami format and compare it to the profiles created by Camisim. Is there any quick way to transform a standard OTU Table into the Cami Biobox Format, like a script or something? I searched extensively but couldn't find anything. 

Thanks again, hopefully this update you mentioned comes out soon!

**Comment by AlphaSquad** [comment]
There is not really a straightforward answer to that since there are so many different profilers and (non-standardized) outputs. If you mean a `biom` profile (e.g. by QIIME) by "standard OTU table" then it might be possible to transform them if they have the `taxonomy` field set. Note though that sometimes the mapping from scientific names to NCBI IDs does not work. 
You can take some inspiration from the script `scripts/get_genomes.py` on how to transform BIOM to CAMI/NCBI. The script does more, i.e. it tries to create a data set as close as possible to the input BIOM profile by downloading corresponding complete genomes (possibly on higher ranks than provided in the profile), but you can probably reuse parts to just do a transformation. This is not really a "quick" way, though, sorry.

**Comment by eparisis** [comment]
Thanks, I will look into those scripts.

I just have one last question about CAMISIM. I've noticed that all the reads produced from nanosim have the same quality scores. Is there a way I can set the configurations for the `--basecaller` option of nanosim and also choose `--max_len` and `--min_len`?

**Comment by AlphaSquad** [comment]
It is not possible "out-of-the-box" (currently), but you can manually change the command lines with which Nanosim will be called in this script: `scripts/ReadSimulationWrapper/readsimulationwrapper.py`, lines `521` to `529`
