### ISSUE TITLE
Unable to download  Mouse Toy  dataset

### ISSUE THREAD

**Issue by richardlett** [CAMI-challenge/CAMISIM#157]
Not sure if this is the best place to inquire, if not I apologize. But I can't seem to download the Mouse Toy dataset

The official DOI repository seems to have  some reads missing (e.g. 40-49):

https://frl.publisso.de/data/frl:6421672/dataset/

Using The java tool and following the given example gives back  errors 
```
$ java -jar camiClient.jar -d https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/CAMISIM_MOUSEGUT . -p fq.gzDownloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_13/reads/anonymous_reads.fq.gz

Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_35/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_pacbio_scaffolds/2018.02.13_14.02.01_sample_49/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_39/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_20/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_3/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_37/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_58/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_pacbio_scaffolds/2018.02.13_14.02.01_sample_61/reads/anonymous_reads.fq.gz
Downloading ./19122017_mousegut_pacbio_scaffolds/2018.02.13_14.02.01_sample_3/reads/anonymous_reads.fq.gz
java.io.IOException: Server returned HTTP response code: 401 for URL: https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/CAMISIM_MOUSEGUT/19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_13/reads/anonymous_reads.fq.gz
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at cami.download.SwiftDownload.urlDownload(SwiftDownload.java:122)
        at cami.download.SwiftDownload.lambda$null$2(SwiftDownload.java:38)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Downloading ./19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_14/reads/anonymous_reads.fq.gz
```

**Comment by AlphaSquad** [comment]
Hm, there have been issues with the openstack download before and typically I refer to the publisso then, but you are right in that the reads for 10 samples are missing. I will try to update the publisso repository, in the meantime I could offer to put the missing reads on our cloud instance for you to download? If that is a solution for you, feel free to email me at adrian.fritz at helmholtz-hzi.de
