### ISSUE TITLE
ERROR: [MetagenomeSimulationPipeline] 'M' in line 122

### ISSUE THREAD

**Issue by kangxiongbin** [CAMI-challenge/CAMISIM#175]
Hi,
I encouter below problem. How to deal with? Thank you very much!

2023-11-21 07:24:37 INFO: [MetadataReader 14212213139] Reading file: '/prj/hybrid-assembly/tmp/tmpfkd2zgz6/read_start_positionsz_npvgow'
2023-11-21 07:24:38 ERROR: [MetagenomeSimulationPipeline] 'M' in line 122
2023-11-21 07:24:38 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

Best,
Xiongbin

**Comment by AlphaSquad** [comment]
Without more context it is very hard to tell what is going wrong. CAMISIM fails during creation of the binning gold standard of a non-anonymized data set, you could try anonymizing the data and see if the error persists.

**Comment by kangxiongbin** [comment]
When I anonymize the data, there are new error. 

Is there any other context I need to provide that could help address the issue? Thanks a lot!

2023-11-27 14:19:57 INFO: [FastaAnonymizer 19015157346] Shuffle and anonymize '/prj/hybrid-assembly/tmp/tmpxg2za0a9/tmpttsv6pfx'
2023-11-27 14:20:01 INFO: [MetadataReader 13638968142] Reading file: '/prj/phasebook/kang/jiangbin/data/simulated_illumina/result_20231120/internal/genome_locations.tsv'
2023-11-27 14:20:01 INFO: [MetadataReader 37614179115] Reading file: '/prj/phasebook/kang/jiangbin/data/simulated_illumina/result_20231120/internal/meta_data.tsv'
2023-11-27 14:20:01 INFO: [MetadataReader 53439442268] Reading file: '/prj/hybrid-assembly/tmp/tmpxg2za0a9/read_start_positionsy4xuuud_'
2023-11-27 14:20:02 INFO: [MetadataReader 87656674631] Reading file: '/prj/hybrid-assembly/tmp/tmpxg2za0a9/tmpju5r9gi8'
2023-11-27 14:20:02 ERROR: [MetagenomeSimulationPipeline] 'KM217573_CpGV-S' in line 117
2023-11-27 14:20:02 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
Traceback (most recent call last):
  File "/prj/metastrain/software/camisim2/CAMISIM/metagenomesimulation.py", line 872, in <module>
    pipeline.run_pipeline()
  File "/prj/metastrain/software/camisim2/CAMISIM/metagenomesimulation.py", line 140, in run_pipeline
    self._project_file_folder_handler.remove_directory_temp()
  File "/prj/metastrain/software/camisim2/CAMISIM/scripts/projectfilefolderhandle.py", line 142, in remove_directory_temp
    shutil.rmtree(self._tmp_dir)
  File "/prj/metastrain/software/conda/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/prj/metastrain/software/conda/lib/python3.8/shutil.py", line 642, in _rmtree_safe_fd
    onerror(os.lstat, fullname, sys.exc_info())
  File "/prj/metastrain/software/conda/lib/python3.8/shutil.py", line 639, in _rmtree_safe_fd
    orig_st = entry.stat(follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: 'tmpziwxh4js'

**Comment by AlphaSquad** [comment]
Hm, this is something I have never encountered, it seems CAMISIM fails to remove the temporary files. This makes me think that it might be a problem with permissions - it would mean though that you are allowed to create but not delete files in `/tmp` which is odd.
Could you try to change the `temp_directory` to a path you definitely have full access to?
