### ISSUE TITLE
Error with default run defaults/mini_config.ini 

### ISSUE THREAD

**Issue by Malfoy** [CAMI-challenge/CAMISIM#50]
I installed all dependencies and I still obtain "Error" with the default command line and I'm running out of ideas.

Thanks in advance for the help.

2019-04-14 15:02:58 INFO: [GenomePreparation 11874323490] Simulating reads finished
2019-04-14 15:03:07 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2019-04-14 15:03:07 INFO: [MetadataReader 76565746185] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/genome_locations.tsv'
2019-04-14 15:09:19 INFO: [MetagenomeSimulationPipeline] Generate pooled strains gold standard assembly
2019-04-14 15:09:19 INFO: [MetadataReader 40340013719] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/genome_locations.tsv'
2019-04-14 15:09:19 INFO: [MetagenomeSimulationPipeline] Samples used for pooled assembly: '2019.04.14_14.53.22_sample_0', '2019.04.14_14.53.22_sample_1', '2019.04.14_14.53.22_sample_2', '2019.04.14_14.53.22_sample_3', '2019.04.14_14.53.22_sample_4', '2019.04.14_14.53.22_sample_5', '2019.04.14_14.53.22_sample_6', '2019.04.14_14.53.22_sample_7', '2019.04.14_14.53.22_sample_8', '2019.04.14_14.53.22_sample_9'
2019-04-14 15:09:19 INFO: [Validator 17733368889] Creating pooled gold standard
2019-04-14 15:09:19 INFO: [Validator 17733368889] Merging bam files.
2019-04-14 15:11:43 INFO: [MetagenomeSimulationPipeline] Creating binning gold standard
2019-04-14 15:11:43 INFO: [MetadataReader 95469384767] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/genome_locations.tsv'
2019-04-14 15:11:44 INFO: [MetadataReader 8601722415] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/meta_data.tsv'
2019-04-14 15:11:50 INFO: [MetadataReader 44116791807] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpMa8PBz/read_start_positionsAn8Hvz'
2019-04-14 15:11:52 ERROR: [MetagenomeSimulationPipeline] local variable 'file_path_anonymous_gs_mapping' referenced before assignment in line 122
2019-04-14 15:11:52 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

**Comment by AlphaSquad** [comment]
Hm, hard to tell. Could you run the command with the --debug option and send/append the complete log so I can check what might be going wrong?

**Comment by Malfoy** [comment]
Here with the --debug option 

Total CPU time used: 5.44

The random seed for the run: 1303100178

Parameters used during run
	Read Length:	150
	Genome masking 'N' cutoff frequency: 	1 in 150
	Fold Coverage:            4.52936X
	Mean Fragment Length:     270
	Standard Deviation:       27
	Profile Type:             Combined
	ID Tag:                   

Quality Profile(s)
	First Read:   /home/ubuntu/dataBIG/METAG/CAMISIM/tools/art_illumina-2.3.6/profiles/ART_MBARC-26_HiSeq_R1.txt (user's profile)
	Second Read:  /home/ubuntu/dataBIG/METAG/CAMISIM/tools/art_illumina-2.3.6/profiles/ART_MBARC-26_HiSeq_R2.txt (user's profile)

Output files

  FASTQ Sequence Files:
	 the 1st reads: /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/2019.04.15_08.38.37_sample_9/reads/Genome19.01.fq
	 the 2nd reads: /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/2019.04.15_08.38.37_sample_9/reads/Genome19.02.fq

  SAM Alignment File:
	/home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/2019.04.15_08.38.37_sample_9/reads/Genome19.0.sam

2019-04-15 08:48:06 INFO: [GenomePreparation 11874323490] Simulating reads finished
2019-04-15 08:48:15 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2019-04-15 08:48:15 INFO: [MetadataReader 76565746185] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/genome_locations.tsv'
2019-04-15 08:54:23 INFO: [MetagenomeSimulationPipeline] Generate pooled strains gold standard assembly
2019-04-15 08:54:23 INFO: [MetadataReader 40340013719] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/genome_locations.tsv'
2019-04-15 08:54:23 INFO: [MetagenomeSimulationPipeline] Samples used for pooled assembly: '2019.04.14_14.53.22_sample_0', '2019.04.14_14.53.22_sample_1', '2019.04.14_14.53.22_sample_2', '2019.04.14_14.53.22_sample_3', '2019.04.14_14.53.22_sample_4', '2019.04.14_14.53.22_sample_5', '2019.04.14_14.53.22_sample_6', '2019.04.14_14.53.22_sample_7', '2019.04.14_14.53.22_sample_8', '2019.04.14_14.53.22_sample_9', '2019.04.15_08.38.37_sample_0', '2019.04.15_08.38.37_sample_1', '2019.04.15_08.38.37_sample_2', '2019.04.15_08.38.37_sample_3', '2019.04.15_08.38.37_sample_4', '2019.04.15_08.38.37_sample_5', '2019.04.15_08.38.37_sample_6', '2019.04.15_08.38.37_sample_7', '2019.04.15_08.38.37_sample_8', '2019.04.15_08.38.37_sample_9'
2019-04-15 08:54:23 INFO: [Validator 17733368889] Creating pooled gold standard
2019-04-15 08:54:23 INFO: [Validator 17733368889] Merging bam files.
[bam_sort_core] merging from 2 files...
2019-04-15 08:57:44 INFO: [MetagenomeSimulationPipeline] Creating binning gold standard
2019-04-15 08:57:44 DEBUG: [MetagenomeSimulationPipeline] /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpocge6y, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmp7ZNee7, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpojR7Xs, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpd9Ea2V, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpiTlWRg, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpyqTivK, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpU2xo7K, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpOjag3L, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpETHPDS, /home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/tmpQbZnMp
2019-04-15 08:57:44 INFO: [MetadataReader 95469384767] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/genome_locations.tsv'
2019-04-15 08:57:45 INFO: [MetadataReader 8601722415] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/out/internal/meta_data.tsv'
2019-04-15 08:57:51 INFO: [MetadataReader 44116791807] Reading file: '/home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4/read_start_positionsQUpNzz'
2019-04-15 08:57:53 DEBUG: [MetagenomeSimulationPipeline] 
Traceback (most recent call last):
  File "metagenomesimulation.py", line 122, in run_pipeline
    self._create_binning_gs()
  File "metagenomesimulation.py", line 508, in _create_binning_gs
    with open(file_path_anonymous_gs_mapping, 'w') as stream_output:
UnboundLocalError: local variable 'file_path_anonymous_gs_mapping' referenced before assignment


2019-04-15 08:57:53 ERROR: [MetagenomeSimulationPipeline] local variable 'file_path_anonymous_gs_mapping' referenced before assignment in line 122
2019-04-15 08:57:53 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
2019-04-15 08:57:53 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
/home/ubuntu/dataBIG/METAG/CAMISIM/tmp/tmpGE9Pk4

**Comment by AlphaSquad** [comment]
Thanks for pointing this out, this was indeed a critical bug for non-anonymised data sets, can you please confirm that 76291d04e9 fixed it for you?

**Comment by AlphaSquad** [comment]
Hi, could you comment on whether your problem was solved with the latest patch? That would be great, thank you

**Comment by Malfoy** [comment]
Solved ! Thank you for your time and your quick reaction !
