### ISSUE TITLE
error in metagenomesimulation.py

### ISSUE THREAD

**Issue by aspitaleri** [CAMI-challenge/CAMISIM#65]
Hi
related to #49 I got similar problem:

 #PBS -l nodes=1:ppn=1
#PBS -l mem=70GB
python metagenomesimulation.py --debug defaults/mini_config.ini 

2019-08-07 11:22:17 INFO: [FastaAnonymizer] Interweave shuffle and anonymize
2019-08-07 11:22:17 DEBUG: [FastaAnonymizer] get_seeded_random() { seed="$1"; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt < /dev/zero 2>/dev/null; }; python '/lustre2/scratch/Cirillo/SOFT
W/CAMISIM/fastastreamer.py' -input '/tmp/tmpPCfwc7/2019.08.07_11.12.55_sample_0/reads' -format 'fastq' -ext 'fq' | shuf -z --random-source=<(get_seeded_random 3808562586786140696) | tr -d '\000' 
| python '/lustre2/scratch/Cirillo/SOFTW/CAMISIM/anonymizer.py' -prefix 'S0R' -format 'fastq' -map '/tmp/tmpPCfwc7/tmpmd3a2M' -out '/tmp/tmpPCfwc7/tmpt6VS_Z'
shuf: '/dev/fd/63': end of file
2019-08-07 11:23:21 INFO: [MetadataReader 28632919956] Reading file: '/lustre2/scratch/Cirillo/SOFTW/CAMISIM/out/internal/genome_locations.tsv'
2019-08-07 11:23:23 INFO: [MetadataReader 44068977927] Reading file: '/lustre2/scratch/Cirillo/SOFTW/CAMISIM/out/internal/meta_data.tsv'
2019-08-07 11:23:23 INFO: [MetadataReader 76495163535] Reading file: '/tmp/tmpPCfwc7/tmpmd3a2M'
2019-08-07 11:23:23 DEBUG: [MetagenomeSimulationPipeline] 
Traceback (most recent call last):
  File "metagenomesimulation.py", line 117, in run_pipeline
    self._anonymize_data(list_of_output_gsa, file_path_output_gsa_pooled)
  File "metagenomesimulation.py", line 635, in _anonymize_data
    file_path_genome_locations, file_path_metadata, file_path_anonymous_mapping_tmp, stream_output
  File "/lustre2/scratch/Cirillo/SOFTW/CAMISIM/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 368, in gs_read_mapping
    dict_anonymous_to_read_id = self.get_dict_anonymous_to_original_id(file_path_id_map)
  File "/lustre2/scratch/Cirillo/SOFTW/CAMISIM/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 142, in get_dict_anonymous_to_original_id
    dict_mapping = table.get_map(1, 0)
  File "/lustre2/scratch/Cirillo/SOFTW/CAMISIM/scripts/MetaDataTable/metadatatable.py", line 613, in get_map
    assert self.has_column(key_column_name), "Column '{}' not found!".format(key_column_name)
AssertionError: Column '1' not found!
2019-08-07 11:23:23 ERROR: [MetagenomeSimulationPipeline] Column '1' not found! in line 117
2019-08-07 11:23:23 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
2019-08-07 11:23:23 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
/tmp/tmpPCfwc7

any help?
Thanks

**Comment by aspitaleri** [comment]
additional comment. Putting:
anonymous=False
CAMISIM end properly.

**Comment by AlphaSquad** [comment]
Hm that is odd. Are you running the docker version by any chance? Also it seems like you are running CAMISIM in a cluster environment, maybe that is causing some trouble (even though I don't know why this should be the case).
Are you okay with not running the anonymization right now while I investigate the issue?

**Comment by aspitaleri** [comment]
I am not using docker. I have just git clone CAMISIM. Yes indeed I am using on the cluster. I will test in on my pc too.
The anonymization step needs for?

**Comment by aspitaleri** [comment]
In the error there is
shuf: '/dev/fd/63': end of file
not sure whether is okay ...

**Comment by aspitaleri** [comment]
The same version, same input in my notebook worked fine.

**Comment by AlphaSquad** [comment]
> In the error there is
> shuf: '/dev/fd/63': end of file
> not sure whether is okay ...

Yeah, that did look odd to me as well, that it why I suspect it is the cluster somehow - it seems like a file is not created or not where CAMISIM expects it to be. I don't really see why CAMISIM would not work on a cluster though, I ran it on ours and it worked perfectly fine. Does this crash occur every time in a reproducible manner?

**Comment by aspitaleri** [comment]
yes the crash occur every time in a reproducible manner.

**Comment by AlphaSquad** [comment]
> I am not using docker. I have just git clone CAMISIM. Yes indeed I am using on the cluster. I will test in on my pc too.
> The anonymization step needs for?

The anonymization step is only needed if you do not want the genome sources to be visible from looking at the reads, i.e. the read simulator uses the given genome name as name for the reads.

Unfortunately I am not sure how to test CAMISIMs behaviour on a cluster environment to find out where exactly the bug is buried
