### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by sanpande** [CAMI-challenge/CAMISIM#69]
Hi, I am trying to use CAMISIM to simulate metagenome. I tried using the docker version and got the following error:
$ docker run -it cami/camisim:latest  metagenome_from_profile.py -c sp_config.ini
NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site...
Done. Parsing...
Loading node names...
2177582 names loaded.
260572 synonyms loaded.
Loading nodes...
2177582 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /root/.etetoolkit/taxa.sqlite ...
2177000 generating entries... 
Uploading to /root/.etetoolkit/taxa.sqlite

Inserting synonyms:      260000 
Inserting taxid merges:  55000 
Inserting taxids:       2175000 
2019-10-23 22:14:34 WARNING: [root] Max strains per OTU not set, using default (3)
2019-10-23 22:14:34 WARNING: [root] Mu and sigma have not been set, using defaults (1,2)
Traceback (most recent call last):
  File "metagenome_from_profile.py", line 87, in <module>
    config = GG.generate_input(args) # total number of genomes and path to updated config
  File "/usr/local/bin/scripts/get_genomes.py", line 283, in generate_input
    tax_profile = read_taxonomic_profile(args.profile, config, args.samples)
  File "/usr/local/bin/scripts/get_genomes.py", line 26, in read_taxonomic_profile
    table = biom.load_table(biom_profile)
  File "/usr/local/lib/python2.7/dist-packages/biom/parse.py", line 652, in load_table
    with biom_open(f) as fp:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/biom/util.py", line 443, in biom_open
    if os.path.getsize(fp) == 0:
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
TypeError: coercing to Unicode: need string or buffer, NoneType found
Exception AttributeError: "'NoneType' object has no attribute '_map_logfile_handler'" in <bound method LoggingWrapper.__del__ of <scripts.loggingwrapper.LoggingWrapper object at 0x7f7529e81ed0>> ignored
$ packet_write_wait: Connection to 10.14.250.6 port 22: Broken pipe

-------------------
I also tried using the local install version but got an error for samtools

2019-10-23 16:36:38 ERROR: [Validator 53545039778] Task failed with return code: 1, task: /path_to/CAMISIM/tools/samtools-1.3/samtools view -bS /tmp/tmp0hJ55D/2019.10.23_15.54.17_sample_0/reads/13.sam | /path_to/CAMISIM/software/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /path_to/CAMISIM/output/2019.10.23_15.54.17_sample_0/bam/13.bam -O bam -T /tmp/tmp0hJ55D/temp_sam_to_sorted_bamSpBoUm; /path_to/CAMISIM/software/CAMISIM/tools/samtools-1.3/samtools index /path_to/output/2019.10.23_15.54.17_sample_0/bam/13.bam

**Comment by sanpande** [comment]
Hi, Thanks for your help. The command worked although I had to change the samtools version. thanks.
