### ISSUE TITLE
error in MetagenomeSimulationPipeline: "Key column is not unique!"

### ISSUE THREAD

**Issue by cwillian1** [CAMI-challenge/CAMISIM#76]
Hi, I'm trying to to simulate a metagenome data based on the biom file named "table.biom", but every time i run my file i get the following error : 

> 

**COMMAND** : python2.7 metagenome_from_profile.py -p input/table.biom

NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site...
Done. Parsing...
Loading node names...
2231464 names loaded.
267167 synonyms loaded.
Loading nodes...
2231464 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /home/rommel/.etetoolkit/taxa.sqlite ...
2231000 generating entries...
Uploading to /home/rommel/.etetoolkit/taxa.sqlite

Inserting synonyms:      265000
Inserting taxid merges:  55000
Inserting taxids:       2230000
2020-03-13 14:47:12 WARNING: [root] Max strains per OTU not set, using default (3)
2020-03-13 14:47:12 WARNING: [root] Mu and sigma have not been set, using defaults (1,2)
2020-03-13 14:47:14 WARNING: [root] Some OTUs could not be mapped
2020-03-13 15:13:35 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2020-03-13 15:13:35 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2020-03-13 15:13:35 INFO: [MetadataReader] Reading file: '/usr/local/CAMISIM/out/genome_to_id.tsv'
2020-03-13 15:31:35 INFO: [MetadataReader 10730545418] Reading file: '/usr/local/CAMISIM/out/metadata.tsv'
2020-03-13 15:31:35 INFO: [MetadataReader 63391851204] Reading file: '/usr/local/CAMISIM/out/internal/genome_locations.tsv'
2020-03-13 15:31:35 ERROR: [MetadataReader 63391851204] Key column is not unique! Key: 'Genome2.0'
2020-03-13 15:31:35 ERROR: [MetagenomeSimulationPipeline] "Key column is not unique! Key: 'Genome2.0'" in line 74
2020-03-13 15:31:35 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

> 
I also tried CAMISIM on docker  and the same output was generated.

[table.tar.gz](https://github.com/CAMI-challenge/CAMISIM/files/4363907/table.tar.gz)

What's that error and how can I edit the same to fix this Key column error. Thanks for all the help in advance!

**Comment by AlphaSquad** [comment]
Hi, thank you for your interest in CAMISIM.
Using your table, I was actually able to run CAMISIM. Could you make sure that your output folder is empty every time before you run CAMISIM? If the problem persists, could you run CAMISIM with the `--debug` flag and post the relevant lines here?

**Comment by AlphaSquad** [comment]
Did that solve the problem?

**Comment by cwillian1** [comment]
Hi, unfortunately it didn't solve. I got the following output at the end:
"2020-05-01 00:32:48 INFO: [MetagenomeSimulationPipeline] Anonymize Data
2020-05-01 00:32:48 DEBUG: [MetagenomeSimulationPipeline] /tmp/tmp7Pspcn/tmphgEioA
2020-05-01 00:32:48 INFO: [FastaAnonymizer] Interweave shuffle and anonymize
2020-05-01 00:32:48 DEBUG: [FastaAnonymizer] get_seeded_random() { seed="$1"; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt < /dev/zero 2>/dev/null; }; python '/usr/local/bin/fastastreamer.py' -input '/tmp/tmp7Pspcn/2020.04.30_22.19.01_sample_0/reads' -format 'fastq' -ext 'fq' | shuf -z --random-source=<(get_seeded_random 9071709612437831311) | tr -d '\000' | python '/usr/local/bin/anonymizer.py' -prefix 'S0R' -format 'fastq' -map '/tmp/tmp7Pspcn/tmpAq1E_p' -out '/tmp/tmp7Pspcn/tmp89kEbv'
2020-05-01 03:01:52 INFO: [MetadataReader 67617452792] Reading file: '/output2/internal/genome_locations.tsv'
2020-05-01 03:02:37 INFO: [MetadataReader 62586115832] Reading file: '/output2/internal/meta_data.tsv'
2020-05-01 03:02:37 INFO: [MetadataReader 21526797271] Reading file: '/tmp/tmp7Pspcn/tmpAq1E_p'
2020-05-01 03:10:25 INFO: [FastaAnonymizer 41057992627] Shuffle and anonymize '/tmp/tmp7Pspcn/tmphgEioA'
2020-05-01 03:10:25 DEBUG: [FastaAnonymizer 41057992627] get_seeded_random() { seed="$1"; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt < /dev/zero 2>/dev/null; }; python '/usr/local/bin/fastastreamer.py' -input '/tmp/tmp7Pspcn/tmphgEioA' -format 'fasta' -s | shuf -z --random-source=<(get_seeded_random 1700072152109590426) | tr -d '\000' | python '/usr/local/bin/anonymizer.py' -prefix 'S0C' -format 'fasta' -map '/tmp/tmp7Pspcn/tmpfjp8ZW' -out '/tmp/tmp7Pspcn/tmpW_n2Mu' -s
2020-05-01 03:15:40 INFO: [MetadataReader 79000131363] Reading file: '/output2/internal/genome_locations.tsv'
2020-05-01 03:16:23 INFO: [MetadataReader 20349466676] Reading file: '/output2/internal/meta_data.tsv'
2020-05-01 03:16:23 INFO: [MetadataReader 69353688482] Reading file: '/tmp/tmp7Pspcn/read_start_positionsf_tTsg'
2020-05-01 03:21:18 INFO: [MetadataReader 46788092217] Reading file: '/tmp/tmp7Pspcn/tmpfjp8ZW'
2020-05-01 03:21:19 ERROR: [MetadataReader 46788092217] Key column is not unique! Key: 'HE774682.1_from_2840475_to_2840624_total_150'
2020-05-01 03:21:19 DEBUG: [MetagenomeSimulationPipeline]
Traceback (most recent call last):
  File "./metagenomesimulation.py", line 117, in run_pipeline
    self._anonymize_data(list_of_output_gsa, file_path_output_gsa_pooled)
  File "./metagenomesimulation.py", line 678, in _anonymize_data
    list_file_paths_read_positions, stream_output
  File "/usr/local/bin/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 343, in gs_contig_mapping
    dict_sequence_name_to_anonymous = self.get_dict_sequence_name_to_anonymous(file_path_id_map)
  File "/usr/local/bin/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 161, in get_dict_sequence_name_to_anonymous
    dict_mapping = table.get_map(0, 1)
  File "/usr/local/bin/scripts/MetaDataTable/metadatatable.py", line 631, in get_map
    raise KeyError(msg)
KeyError: "Key column is not unique! Key: 'HE774682.1_from_2840475_to_2840624_total_150'"


2020-05-01 03:21:19 ERROR: [MetagenomeSimulationPipeline] "Key column is not unique! Key: 'HE774682.1_from_2840475_to_2840624_total_150'" in line 117
2020-05-01 03:21:19 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
2020-05-01 03:21:19 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
/tmp/tmp7Pspcn
"

**Comment by AlphaSquad** [comment]
Closed due to inactivity. If you still have problems with this, please feel free to reopen.
