### ISSUE TITLE
Converting sam files to bam files failed

### ISSUE THREAD

**Issue by singhbhavya** [CAMI-challenge/CAMISIM#80]
Hi there! I recently downloaded CAMISIM, and seem to be receiving some errors when running the test case. Everything seems to be working fine, until the conversion from sam files to bam files.

This is my code:

` python metagenome_from_profile.py -p defaults/mini.biom `

This is the error:

```
Output files

  FASTQ Sequence Files:
         the 1st reads: /tmp/tmp2BPskA/2020.06.03_15.34.44_sample_1/reads/Genome1.01.fq
         the 2nd reads: /tmp/tmp2BPskA/2020.06.03_15.34.44_sample_1/reads/Genome1.02.fq

  SAM Alignment File:
        /tmp/tmp2BPskA/2020.06.03_15.34.44_sample_1/reads/Genome1.0.sam

2020-06-03 16:29:27 INFO: [GenomePreparation 84681769869] Simulating reads finished
[bam_sort_core] merging from 6 files...
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[bam_merge_core] '/tmp/tmp2BPskA/temp_sam_to_sorted_bammdFwe1.0002.bam' is truncated. Continue anyway.
[bam_sort_core] merging from 8 files...
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[bam_merge_core] '/tmp/tmp2BPskA/temp_sam_to_sorted_bam1aBOiT.0002.bam' is truncated. Continue anyway.
2020-06-03 16:40:10 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2020-06-03 16:40:10 INFO: [MetadataReader 55865984800] Reading file: '/home/bsingh/bin/CAMISIM/out/internal/genome_locations.tsv'
2020-06-03 16:48:02 INFO: [MetagenomeSimulationPipeline] Generate pooled strains gold standard assembly
2020-06-03 16:48:02 INFO: [MetadataReader 78972166476] Reading file: '/home/bsingh/bin/CAMISIM/out/internal/genome_locations.tsv'
2020-06-03 16:48:02 INFO: [MetagenomeSimulationPipeline] Samples used for pooled assembly: '2020.06.03_15.34.44_sample_0', '2020.06.03_15.34.44_sample_1'
2020-06-03 16:48:02 INFO: [Validator 62485088175] Creating pooled gold standard
2020-06-03 16:48:02 INFO: [Validator 62485088175] Merging bam files.
2020-06-03 16:48:02 WARNING: [Validator 62485088175] List contains only one file: '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_1/bam/Genome2.0.bam'
2020-06-03 16:48:03 WARNING: [Validator 62485088175] List contains only one file: '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_1/bam/Genome2.1.bam'
[bam_sort_core] merging from 2 files...
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
samtools index: "/tmp/tmp2BPskA/tmpJM6qLp/Genome1.1.bam" is corrupted or unsorted
samtools index: "/tmp/tmp2BPskA/tmpJM6qLp/Genome1.0.bam" is in a format that cannot be usefully indexed
Task failed with return code: 1, task: /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools merge -u - '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_0/bam/Genome1.1.bam' '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_1/bam/Genome1.1.bam' | /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /tmp/tmp2BPskA/tmpJM6qLp/Genome1.1.bam -O bam -T /tmp/tmp2BPskA/temp_merged_to_sorted_bamFbP0lx; /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools index /tmp/tmp2BPskA/tmpJM6qLp/Genome1.1.bam
Task failed with return code: 1, task: /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools merge -u - '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_0/bam/Genome1.0.bam' '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_1/bam/Genome1.0.bam' | /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /tmp/tmp2BPskA/tmpJM6qLp/Genome1.0.bam -O bam -T /tmp/tmp2BPskA/temp_merged_to_sorted_bamYUQlXa; /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools index /tmp/tmp2BPskA/tmpJM6qLp/Genome1.0.bam
2020-06-03 16:55:55 ERROR: [Validator 62485088175] Task failed with return code: 1, task: /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools merge -u - '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_0/bam/Genome1.1.bam' '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_1/bam/Genome1.1.bam' | /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /tmp/tmp2BPskA/tmpJM6qLp/Genome1.1.bam -O bam -T /tmp/tmp2BPskA/temp_merged_to_sorted_bamFbP0lx; /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools index /tmp/tmp2BPskA/tmpJM6qLp/Genome1.1.bam

2020-06-03 16:55:55 ERROR: [Validator 62485088175] Task failed with return code: 1, task: /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools merge -u - '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_0/bam/Genome1.0.bam' '/home/bsingh/bin/CAMISIM/out/2020.06.03_15.34.44_sample_1/bam/Genome1.0.bam' | /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /tmp/tmp2BPskA/tmpJM6qLp/Genome1.0.bam -O bam -T /tmp/tmp2BPskA/temp_merged_to_sorted_bamYUQlXa; /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools index /tmp/tmp2BPskA/tmpJM6qLp/Genome1.0.bam

2020-06-03 16:55:55 ERROR: [Validator 62485088175] Converting sam files to bam files failed.
2020-06-03 16:55:55 ERROR: [MetagenomeSimulationPipeline] Converting sam files to bam files failed. in line 111
2020-06-03 16:55:55 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

```

Any help would be greatly appreciated! Thank you!

**Comment by AlphaSquad** [comment]
Hm, I have never encountered this. Which samtools version are you using? One distributed with CAMISIM or your own?

**Comment by singhbhavya** [comment]
Hi there! I'm using the samtools version that is distributed with CAMISIM (CAMISIM/tools/samtools-1.3/samtools)

**Comment by AlphaSquad** [comment]
The strange thing is that samtools fails for two different genome bam-files with two different errors (and that it report these "EOF marker is absent" errors earlier). Could you run it again from scratch, using the `-debug` flag, deleting all previous output CAMISIM might have produced? Maybe create less data for that test run so it doesn't take that long.
If the problem persists, it might be interesting to look at the temporary data CAMISIM produced, it gets stored when using `-debug`

**Comment by singhbhavya** [comment]
Awesome, thank you! Will do that right now and let you know what I get.

**Comment by singhbhavya** [comment]
This is the error message I get:

```
Quality Profile(s)
        First Read:   /home/bsingh/bin/CAMISIM/tools/art_illumina-2.3.6/profiles/ART_MBARC-26_HiSeq_R1.txt (user's profile)
        Second Read:  /home/bsingh/bin/CAMISIM/tools/art_illumina-2.3.6/profiles/ART_MBARC-26_HiSeq_R2.txt (user's profile)

Output files

  FASTQ Sequence Files:
         the 1st reads: /tmp/tmpT3okWo/2020.06.05_10.04.25_sample_1/reads/Genome2.01.fq
         the 2nd reads: /tmp/tmpT3okWo/2020.06.05_10.04.25_sample_1/reads/Genome2.02.fq

  SAM Alignment File:
        /tmp/tmpT3okWo/2020.06.05_10.04.25_sample_1/reads/Genome2.0.sam

2020-06-05 11:04:22 INFO: [GenomePreparation 66857579434] Simulating reads finished
[bam_sort_core] merging from 11 files...
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[bam_merge_core] '/tmp/tmpT3okWo/temp_sam_to_sorted_bamBeA_fa.0003.bam' is truncated. Continue anyway.
2020-06-05 11:20:25 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2020-06-05 11:20:25 INFO: [MetadataReader 90459293243] Reading file: '/home/bsingh/bin/CAMISIM/out/internal/genome_locations.tsv'
2020-06-05 11:28:10 INFO: [MetagenomeSimulationPipeline] Generate pooled strains gold standard assembly
2020-06-05 11:28:10 INFO: [MetadataReader 15521707443] Reading file: '/home/bsingh/bin/CAMISIM/out/internal/genome_locations.tsv'
2020-06-05 11:28:10 INFO: [MetagenomeSimulationPipeline] Samples used for pooled assembly: '2020.06.05_10.04.25_sample_0', '2020.06.05_10.04.25_sample_1'
2020-06-05 11:28:10 INFO: [Validator 36665849458] Creating pooled gold standard
2020-06-05 11:28:10 INFO: [Validator 36665849458] Merging bam files.
2020-06-05 11:28:10 WARNING: [Validator 36665849458] List contains only one file: '/home/bsingh/bin/CAMISIM/out/2020.06.05_10.04.25_sample_1/bam/Genome2.0.bam'
samtools index: "/tmp/tmpT3okWo/tmp86zCRa/Genome1.0.bam" is in a format that cannot be usefully indexed
Task failed with return code: 1, task: /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools merge -u - '/home/bsingh/bin/CAMISIM/out/2020.06.05_10.04.25_sample_0/bam/Genome1.0.bam' '/home/bsingh/bin/CAMISIM/out/2020.06.05_10.04.25_sample_1/bam/Genome1.0.bam' | /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /tmp/tmpT3okWo/tmp86zCRa/Genome1.0.bam -O bam -T /tmp/tmpT3okWo/temp_merged_to_sorted_bamPRCZpw; /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools index /tmp/tmpT3okWo/tmp86zCRa/Genome1.0.bam
2020-06-05 11:36:07 ERROR: [Validator 36665849458] Task failed with return code: 1, task: /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools merge -u - '/home/bsingh/bin/CAMISIM/out/2020.06.05_10.04.25_sample_0/bam/Genome1.0.bam' '/home/bsingh/bin/CAMISIM/out/2020.06.05_10.04.25_sample_1/bam/Genome1.0.bam' | /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools sort -l 5 -m 1G -o /tmp/tmpT3okWo/tmp86zCRa/Genome1.0.bam -O bam -T /tmp/tmpT3okWo/temp_merged_to_sorted_bamPRCZpw; /home/bsingh/bin/CAMISIM/tools/samtools-1.3/samtools index /tmp/tmpT3okWo/tmp86zCRa/Genome1.0.bam

2020-06-05 11:36:07 ERROR: [Validator 36665849458] Converting sam files to bam files failed.
2020-06-05 11:36:07 DEBUG: [MetagenomeSimulationPipeline]
Traceback (most recent call last):
  File "./metagenomesimulation.py", line 111, in run_pipeline
    file_path_output_gsa_pooled = self._generate_gsa_pooled()
  File "./metagenomesimulation.py", line 453, in _generate_gsa_pooled
    list_of_directory_bam, dict_id_to_file_path_fasta)
  File "/home/bsingh/bin/CAMISIM/scripts/GoldStandardAssembly/goldstandardassembly.py", line 172, in pooled_gold_standard_by_dir
    self.merge_bam_files_by_list_of_dir(list_of_directory_bam, output_dir=self._temp_merges_bam_directory)
  File "/home/bsingh/bin/CAMISIM/scripts/GoldStandardAssembly/samtoolswrapper.py", line 290, in merge_bam_files_by_list_of_dir
    self.merge_bam_files_by_dict(dict_of_bam_files, output_dir)
  File "/home/bsingh/bin/CAMISIM/scripts/GoldStandardAssembly/samtoolswrapper.py", line 257, in merge_bam_files_by_dict
    raise OSError(msg)
OSError: Converting sam files to bam files failed.


2020-06-05 11:36:07 ERROR: [MetagenomeSimulationPipeline] Converting sam files to bam files failed. in line 111
2020-06-05 11:36:07 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
2020-06-05 11:36:07 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
/tmp/tmpT3okWo

```

Let me know which temporary data files to send you!

**Comment by singhbhavya** [comment]
Hi there! Sorry to bother you again, but while I try to work through the samtools issue with the test case above, I've been creating a config file for my own data. 

I will be running a simulation from a .biom profile, and just had a couple of things I wanted to confirm:
1. For this mode, abundance file is NOT required
2. We DO NOT need the following in the config file: number of samples, strain simulation template path, id_to_genome_profile file, metadata input file, total genomes, total real genomes, max_strains_per_OTU, ratio, mode (time series, etc), log mu, log sigma, size of a single sample
3. Just confirming that I can simulate multiple metagenomes in one go, from one biom file? Is there an upper limit for number of metagenome simulations that you recommend?

**Comment by AlphaSquad** [comment]
Hi,
sorry for not having responded earlier. How big are the complete temporary files? Unfortunately I still don't see something which springs to my mind. Do you have the complete log saved somewhere?

Regarding your other questions:
1. Exactly, the abundances will be created from the abundances in the BIOM file
2. Yes, all these will either be calculated by CAMISIM or are not relevant since the information is present in the abundance files
3. I am not entirely sure I understand this question correctly. CAMISIM will create a number of samples based on the samples in the BIOM file and will use the set of genomes present in all samples. If you have two completely "disjunct" metagenomes in one single BIOM file, CAMISIM will create both, but it will be shown as only one, e.g. all genomes from one metagenome will appear as 0-abundant in the gold standards of the other. Theoretically there is no upper limit of the number of samples, but creating many samples can be very time and memory consuming since all bam-files will be merged for creating the gold standard. A 64-sample, 5GB/sample run took around 3 weeks and 100s of GB RAM on a 64 core machine.

**Comment by singhbhavya** [comment]
Hi, thank you so much for your reply!!

The program worked perfectly!! I just successfully ran it to simulate 34 metagenomic samples. I just have one last question about the output files. As expected, I have 34 directories for each of the samples, with the sub-directories "bam", "contigs", and "reads". The contigs directory has the gold standard assembly. The pooled GSA is in the main /out directory.

The individual reads directories have the following files: 1) reads_mapping.tsv.gz, and 2) a number of fastq files for each species/strain in the metagenomic sample (ex: sp1.01.fq.gz, sp1.02.fq.gz).

My question is this: I'm assuming this is normal, and I need to concatenate all the R1 files (ex: sp1.01.fq.gz) and R2 files (ex: sp1.02.fq.gz) to create the raw R1 and R2 fastq files that I can then assemble?

**Comment by AlphaSquad** [comment]
Yes, this is normal if you did not anonymize your data (then all the reads will be concatenated). If you want these as one read set then yes, you described the proceedings - merge all R1 and all R2 files, I hope this works for you.

**Comment by singhbhavya** [comment]
Hi, thank you so much for all of your help so far!! I sincerely apologize for taking up so much of your time with questions. I ran the program one more time, but this time, I decided to anonymize. All the bam files were generated, but I ended up with the following error during the interweave/shuffle/anonymize step of the pipeline: 

```
2020-07-14 22:02:29 ERROR: [MetadataReader 74249821214] Key column is not unique! Key: 'CP000140.1_from_1613872_to_1614021_total_150'
2020-07-14 22:02:29 ERROR: [MetagenomeSimulationPipeline] "Key column is not unique! Key: 'CP000140.1_from_1613872_to_1614021_total_150'" in line 117
2020-07-14 22:02:29 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```

Do you know what I can do about this error?

**Comment by AlphaSquad** [comment]
Sorry, I must have overseen your reply. Could you try running CAMISIM with a different seed and in a completely new environment/folder? I have seen this error before, but have never been able to exactly pinpoint where it comes from.

**Comment by AlphaSquad** [comment]
Closed due to inactivity. If your problem persists, feel free to reopen.
