### ISSUE TITLE
"python metagenome_from_profile.py -p defaults/mini.biom" KeyError

### ISSUE THREAD

**Issue by punnettsun** [CAMI-challenge/CAMISIM#89]
I used the command: "python metagenome_from_profile.py -p defaults/mini.biom" to do the default profile run but ended up getting errors. I have pasted the debug report below. There is a key error that I do not know where it is coming from. I had just recently re-downloaded CAMISIM & re-built the environment so all files used have not been modified in any way. Please let me know what could be wrong. Thank you.

$ python metagenome_from_profile.py -p defaults/mini.biom --debug
2020-09-11 01:24:50 INFO: [root] Using commands:
2020-09-11 01:24:50 INFO: [root] -profile: defaults/mini.biom
2020-09-11 01:24:50 INFO: [root] -tmp: None
2020-09-11 01:24:50 INFO: [root] -community_only: False
2020-09-11 01:24:50 INFO: [root] -ncbi: tools/ncbi-taxonomy_20170222.tar.gz
2020-09-11 01:24:50 INFO: [root] -reference_genomes: tools/assembly_summary_complete_genomes.txt
2020-09-11 01:24:50 INFO: [root] -fill_up: False
2020-09-11 01:24:50 INFO: [root] -o: out/
2020-09-11 01:24:50 INFO: [root] -no_replace: True
2020-09-11 01:24:50 INFO: [root] -seed: None
2020-09-11 01:24:50 INFO: [root] -additional_references: None
2020-09-11 01:24:50 INFO: [root] -samples: None
2020-09-11 01:24:50 INFO: [root] -debug: True
2020-09-11 01:24:50 INFO: [root] -config: defaults/default_config.ini
2020-09-11 01:24:50 WARNING: [root] Max strains per OTU not set, using default (3)
2020-09-11 01:24:50 WARNING: [root] Mu and sigma have not been set, using defaults (1,2)
Traceback (most recent call last):
  File "metagenome_from_profile.py", line 95, in <module>
    config = GG.generate_input(args) # total number of genomes and path to updated config
  File "/home/ec2-user/CAMISIM-master/scripts/get_genomes.py", line 349, in generate_input
    per_rank_map = get_genomes_per_rank(genomes_map, RANKS, MAX_RANK)
  File "/home/ec2-user/CAMISIM-master/scripts/get_genomes.py", line 95, in get_genomes_per_rank
    if ranks[tax_id] in per_rank_map: # if we are a legal rank
KeyError: 1
Exception AttributeError: "'NoneType' object has no attribute '_map_logfile_handler'" in <bound method LoggingWrapper.__del__ of <scripts.loggingwrapper.LoggingWrapper object at 0x7f20db4ab3d0>> ignored

**Comment by AlphaSquad** [comment]
Duplication of #87 
I will close this here and keep you updated there. It seems like something seriously broke.
