### ISSUE TITLE
KeyError and empty bam file when running CAMISIM with nanopore

### ISSUE THREAD

**Issue by MaxenceQueyrel** [CAMI-challenge/CAMISIM#99]
Hello,

I am trying to use CAMISIM to simulate nanopore reads.
I am on the branch nanosim and I downloaded the NanoSim github here https://github.com/bcgsc/NanoSim.
Python command is python 2.7 and I have also Python 3.6 (called by NanoSim).

I run CAMISIM using the example config file "mini_nanosim.ini" (after changing path) with the command : 

`python /CAMISIM/metagenomesimulation.py mini_config_test_nanopore.ini
`
 and I get the following error : 

```
2020-11-16 14:30:49 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2020-11-16 14:30:49 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2020-11-16 14:30:49 INFO: [MetadataReader] Reading file: '/CAMISIM/defaults/genome_to_id.tsv'
2020-11-16 14:31:42 INFO: [MetagenomeSimulationPipeline] Design Communities
2020-11-16 14:31:42 INFO: [CommunityDesign] Drawing strains.
2020-11-16 14:31:42 INFO: [MetadataReader 82380310288] Reading file: '/CAMISIM/defaults/metadata.tsv'
2020-11-16 14:31:42 INFO: [MetadataReader 28547833133] Reading file: '/CAMISIM/defaults/genome_to_id.tsv'
2020-11-16 14:31:42 INFO: [CommunityDesign] Validating raw sequence files!
2020-11-16 14:32:34 INFO: [NcbiTaxonomy] Building taxonomy tree...
2020-11-16 14:32:34 INFO: [NcbiTaxonomy] Reading 'nodes' file:	'/tmp/tmpRGR3xY/NCBI/nodes.dmp'
2020-11-16 14:32:52 INFO: [NcbiTaxonomy] Reading 'names' file:	'/tmp/tmpRGR3xY/NCBI/names.dmp'
2020-11-16 14:32:54 INFO: [NcbiTaxonomy] Reading 'merged' file:	'/tmp/tmpRGR3xY/NCBI/merged.dmp'
2020-11-16 14:32:55 INFO: [NcbiTaxonomy] Done (21.0s)
2020-11-16 14:32:55 INFO: [MetagenomeSimulationPipeline] Move Genomes
2020-11-16 14:32:56 INFO: [MetagenomeSimulationPipeline] Read simulation
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Reading distribution file
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Reading genome location file
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads using ReadSimulationNanosim readsimulator...
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome15.0: '/test_nanopore/source_genomes/GCA_000227705.3_ASM22770v3.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome14.0: '/test_nanopore/source_genomes/GCA_000006785.2_ASM678v2.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome11.0: '/test_nanopore/source_genomes/GCA_000255115.3_ASM25511v3.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome24.0: '/test_nanopore/source_genomes/GCA_000025905.1_ASM2590v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome12.0: '/test_nanopore/source_genomes/GCA_000231385.3_ASM23138v3.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome18.0: '/test_nanopore/source_genomes/GCA_000023785.1_ASM2378v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome17.0: '/test_nanopore/source_genomes/GCA_000242255.3_ASM24225v3.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome16.0: '/test_nanopore/source_genomes/GCA_000022345.1_ASM2234v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome19.0: '/test_nanopore/source_genomes/GCA_000013785.1_ASM1378v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome2.0: '/test_nanopore/source_genomes/GCA_000445015.1_ASM44501v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome4.0: '/test_nanopore/source_genomes/GCA_001877055.1_ASM187705v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome4.1: '/test_nanopore/source_genomes/GCA_000092985.1_ASM9298v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome5.0: '/test_nanopore/source_genomes/GCA_000143845.1_ASM14384v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome3.0: '/test_nanopore/source_genomes/GCA_000265425.1_ASM26542v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome20.0: '/test_nanopore/source_genomes/GCA_000439255.1_ASM43925v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome6.0: '/test_nanopore/source_genomes/GCA_000092825.1_ASM9282v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome23.0: '/test_nanopore/source_genomes/GCA_000235405.3_ASM23540v3.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome9.0: '/test_nanopore/source_genomes/GCA_000013285.1_ASM1328v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome7.0: '/test_nanopore/source_genomes/GCA_000325705.1_ASM32570v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome13.0: '/test_nanopore/source_genomes/GCA_000233715.3_ASM23371v3.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome10.0: '/test_nanopore/source_genomes/GCA_001692755.1_ASM169275v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome10.1: '/test_nanopore/source_genomes/GCA_000015865.1_ASM1586v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome8.0: '/test_nanopore/source_genomes/GCA_000092125.1_ASM9212v1.fa'
2020-11-16 14:32:56 INFO: [GenomePreparation 75339803532] Simulating reads from Genome22.0: '/test_nanopore/source_genomes/GCA_000143985.1_ASM14398v1.fa'

running the code with following parameters:

ref_g /test_nanopore/source_genomes/GCA_000227705.3_ASM22770v3.fa
model_prefix /CAMISIM/tools/nanosim_profile/mbarc
out /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome15.0
number 189
perfect False
kmer_bias None
basecaller None
dna_type linear
strandness None
sd_len None
median_len None
max_len inf
min_len 50
fastq False
num_threads 1
2020-11-16 14:33:00: /NanoSim/src/simulator.py genome -n 189 -rg /test_nanopore/source_genomes/GCA_000227705.3_ASM22770v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome15.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1778994460
2020-11-16 14:33:00: Read in reference 
2020-11-16 14:33:00: Read error profile
2020-11-16 14:33:00: Read KDF of unaligned reads
/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/NanoSim/src/simulator.py", line 1705, in <module>
    main()
  File "/NanoSim/src/simulator.py", line 1602, in main
    read_profile(ref_g, None, number, model_prefix, perfect, args.mode, strandness, None, False, dna_type, None)
  File "/NanoSim/src/simulator.py", line 411, in read_profile
    kde_unaligned = joblib.load(model_prefix + "_unaligned_length.pkl")
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/anaconda3/envs/py36/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 0

...

2020-11-16 14:33:16 ERROR: [GenomePreparation 75339803532] 24 commands returned errors!
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 189 -rg /test_nanopore/source_genomes/GCA_000227705.3_ASM22770v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome15.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1778994460
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 4192 -rg /test_nanopore/source_genomes/GCA_000006785.2_ASM678v2.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome14.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 540968736
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 4 -rg /test_nanopore/source_genomes/GCA_000255115.3_ASM25511v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome11.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1847505584
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 1 -rg /test_nanopore/source_genomes/GCA_000025905.1_ASM2590v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome24.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 4229332308
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 2608 -rg /test_nanopore/source_genomes/GCA_000231385.3_ASM23138v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome12.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1294107792
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 476 -rg /test_nanopore/source_genomes/GCA_000023785.1_ASM2378v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome18.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 573380146
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 5 -rg /test_nanopore/source_genomes/GCA_000242255.3_ASM24225v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome17.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 2165629018
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 171 -rg /test_nanopore/source_genomes/GCA_000022345.1_ASM2234v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome16.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 170568345
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 84 -rg /test_nanopore/source_genomes/GCA_000013785.1_ASM1378v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome19.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1703660942
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 164 -rg /test_nanopore/source_genomes/GCA_000445015.1_ASM44501v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome2.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1661055959
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 93 -rg /test_nanopore/source_genomes/GCA_001877055.1_ASM187705v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome4.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1577639000
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 2084 -rg /test_nanopore/source_genomes/GCA_000092985.1_ASM9298v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome4.1 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1713385205
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 4 -rg /test_nanopore/source_genomes/GCA_000143845.1_ASM14384v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome5.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 4245153097
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 17 -rg /test_nanopore/source_genomes/GCA_000265425.1_ASM26542v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome3.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1557933273
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 10432 -rg /test_nanopore/source_genomes/GCA_000439255.1_ASM43925v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome20.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1329514040
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 39 -rg /test_nanopore/source_genomes/GCA_000092825.1_ASM9282v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome6.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1168871081
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 7466 -rg /test_nanopore/source_genomes/GCA_000235405.3_ASM23540v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome23.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 2333396874
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 1124 -rg /test_nanopore/source_genomes/GCA_000013285.1_ASM1328v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome9.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 923704084
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 98 -rg /test_nanopore/source_genomes/GCA_000325705.1_ASM32570v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome7.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1550755104
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 1162 -rg /test_nanopore/source_genomes/GCA_000233715.3_ASM23371v3.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome13.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 2302536188
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 55 -rg /test_nanopore/source_genomes/GCA_001692755.1_ASM169275v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome10.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 1923521920
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 646 -rg /test_nanopore/source_genomes/GCA_000015865.1_ASM1586v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome10.1 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 3440135223
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 3894 -rg /test_nanopore/source_genomes/GCA_000092125.1_ASM9212v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome8.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 3605027576
Task failed with return code: 1, task: python3 /NanoSim/src/simulator.py genome -n 29 -rg /test_nanopore/source_genomes/GCA_000143985.1_ASM14398v1.fa -o /tmp/tmpI84UbQ/2020.11.16_14.30.49_sample_0/reads/Genome22.0 -c /CAMISIM/tools/nanosim_profile/mbarc --seed 2102807138
2020-11-16 14:33:16 INFO: [GenomePreparation 75339803532] Simulating reads finished
2020-11-16 14:33:16 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2020-11-16 14:33:16 INFO: [MetadataReader 34032287823] Reading file: '/test_nanopore/internal/genome_locations.tsv'
2020-11-16 14:33:16 ERROR: [MetagenomeSimulationPipeline] Empty bam file list in line 106
2020-11-16 14:33:16 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```
The KeyError is repeated for each genome.

The config file I used is written just bellow :
```
[Main]
seed=632741178
phase=0
max_processors=2
dataset_id=RL
output_directory=/test_nanopore
temp_directory=/tmp
gsa=True
pooled_gsa=True
anonymous=True
compress=1

[ReadSimulator]
readsim=/NanoSim/src/simulator.py
error_profiles=/CAMISIM/tools/nanosim_profile/
samtools=/CAMISIM/tools/samtools-1.3/samtools
profile=mbarc
size=0.1
type=nanosim
fragments_size_mean=
fragment_size_standard_deviation=

[CommunityDesign]
#distribution_file_paths=/home/maxence/Documents/these/data/genome/abundance_balanced_506_species.tsv
ncbi_taxdump=/CAMISIM/tools/ncbi-taxonomy_20170222.tar.gz
strain_simulation_template=/CAMISIM/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
number_of_samples=1

[community0]
metadata=/CAMISIM/defaults/metadata.tsv
id_to_genome_file=/CAMISIM/defaults/genome_to_id.tsv
id_to_gff_file=
genomes_total=24
genomes_real=24
max_strains_per_otu=1
ratio=1
mode=differential
log_mu=1
log_sigma=2
gauss_mu=1
gauss_sigma=1
view=False
```

I hope there is enough information for you to be able to help me.

Thank you,
Maxence.

**Comment by AlphaSquad** [comment]
I have been investigating this, because it looks like it is related to a python3 library NanoSim is using/importing. It seems like they had this issue as well: https://github.com/bcgsc/NanoSim/issues/81
It seems like they resolved it, so it might be possible that the latest NanoSim version works again?

**Comment by MaxenceQueyrel** [comment]
Hi @AlphaSquad, thank you for your answer, you pointed me in the right direction. I effectively ran CAMISIM using NanoSim with success.
However, I had to change two scripts in CAMISIM because I still had issues.

First in scripts/ReadSimulationWrapper/readsimulationwrapper.py, function _sam_from_reads, I changed:
`prefix = f.rsplit("_",2)[0] # get basename`
With
`prefix = f.rsplit("_",3)[0] # get basename`
Because the prefix kept a "_[un]aligned" in the name which produces an error when accessing to the value of the id_to_cigar_map dictionary.

And in scripts/ReadSimulationWrapper/sam_from_reads.py, function write_sam, I changed:
`name, start, align_status, index, strand, soffset, align_length, eoffset = line.strip().split('_')`
With
`name, start, align_status, index, strand, soffset, align_length, eoffset = line.strip().replace(';','_').split('_')`
Because sometimes in the line there is a ";" instead of "_", I think it happens when there is "aligned" instead of "unaligned" in the line.

have you ever encountered this kind of problem before ?

Best,
Maxence.

**Comment by AlphaSquad** [comment]
Great, I am happy that you got it to run. I haven't encountered this problem before, but I was using an older NanoSim version nad didn't try the latest version so far. Unfortunately everytime something in the output formats changes in the simulators, the scripts in CAMISIM break. I will try to find out whether this is the case here.
In the meantime, is your solution something you can live with?

**Comment by MaxenceQueyrel** [comment]
Hi @AlphaSquad, I understand the difficulty of maintenance.
I have tested today another configuration to try something different than the default files.

I had to change the function convert_fasta in scripts/ReadSimulationWrapper/sam_from_reads.py:

`record.id = fixed_names[record.id.split("_")[0]] + "-" + record.id.split("_")[3] # this is the index of the read`
`record.description = fixed_names[record.description.split("_")[0]] + "-" + record.description.split("_")[3]`

with

`record.id = fixed_names[record.id.split("_")[0].replace("-","_")] + "-" + record.id.split("_")[3] # this is the index of the read`
`record.description = fixed_names[record.description.split("_")[0].replace("-","_")] + "-" + record.description.split("_")[3]`

Because of key error again and now it seems to work.
So yes I think I can use it as is for the moment thank you.
